const run = async () => {
  console.log(hello);
}

run().catch(console.error)


